
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";



const App = lazy(() => import("./pages/App.tsx"));
const ConfigPage = lazy(() => import("./pages/ConfigPage.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const EditTemplatePage = lazy(() => import("./pages/EditTemplatePage.tsx"));
const EmailInboxPage = lazy(() => import("./pages/EmailInboxPage.tsx"));
const EmailPage = lazy(() => import("./pages/EmailPage.tsx"));
const EmailTemplatesPage = lazy(() => import("./pages/EmailTemplatesPage.tsx"));
const ImapInboxPage = lazy(() => import("./pages/ImapInboxPage.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const ManageTemplatesPage = lazy(() => import("./pages/ManageTemplatesPage.tsx"));
const ProcessEmailDocumentPage = lazy(() => import("./pages/ProcessEmailDocumentPage.tsx"));
const ReportsPage = lazy(() => import("./pages/ReportsPage.tsx"));

export const userRoutes: RouteObject[] = [


	{ path: "/", element: <App />},
	{ path: "/config-page", element: <UserGuard><ConfigPage /></UserGuard>},
	{ path: "/configpage", element: <UserGuard><ConfigPage /></UserGuard>},
	{ path: "/dashboard-page", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/dashboardpage", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/edit-template-page", element: <UserGuard><EditTemplatePage /></UserGuard>},
	{ path: "/edittemplatepage", element: <UserGuard><EditTemplatePage /></UserGuard>},
	{ path: "/email-inbox-page", element: <UserGuard><EmailInboxPage /></UserGuard>},
	{ path: "/emailinboxpage", element: <UserGuard><EmailInboxPage /></UserGuard>},
	{ path: "/email-page", element: <UserGuard><EmailPage /></UserGuard>},
	{ path: "/emailpage", element: <UserGuard><EmailPage /></UserGuard>},
	{ path: "/email-templates-page", element: <UserGuard><EmailTemplatesPage /></UserGuard>},
	{ path: "/emailtemplatespage", element: <UserGuard><EmailTemplatesPage /></UserGuard>},
	{ path: "/imap-inbox-page", element: <UserGuard><ImapInboxPage /></UserGuard>},
	{ path: "/imapinboxpage", element: <UserGuard><ImapInboxPage /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/manage-templates-page", element: <UserGuard><ManageTemplatesPage /></UserGuard>},
	{ path: "/managetemplatespage", element: <UserGuard><ManageTemplatesPage /></UserGuard>},
	{ path: "/process-email-document-page", element: <UserGuard><ProcessEmailDocumentPage /></UserGuard>},
	{ path: "/processemaildocumentpage", element: <UserGuard><ProcessEmailDocumentPage /></UserGuard>},
	{ path: "/reports-page", element: <UserGuard><ReportsPage /></UserGuard>},
	{ path: "/reportspage", element: <UserGuard><ReportsPage /></UserGuard>},

];
